[package]
name = "serechat-desktop"
description = "Native GPU-rendered SereChat desktop client."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "serechat"
path = "src/main.rs"

[dependencies]
serechat.workspace = true
winit.workspace = true
wgpu.workspace = true
ttf-parser.workspace = true
bytemuck.workspace = true
arboard.workspace = true
png.workspace = true
zune-jpeg.workspace = true
serde_json.workspace = true

[lints]
workspace = true
